import "./globals.css";
import Script from "next/script";
import { Providers, Header, Footer } from "@/components";
import localFont from "next/font/local";

const pretendard = localFont({
    src: "./PretendardVariable.woff2",
    display: "swap",
    variable: "--font-pretendard",
});

export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({ children }) {
    return (
        <html lang="ko">
            <head>
                <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@20,300,0..1,-50..200" />
                <Script
                    type="text/javascript"
                    src={`//dapi.kakao.com/v2/maps/sdk.js?appkey=${process.env.NEXT_PUBLIC_KAKAO_JAVA_SCRIPT_KEY}&libraries=services&autoload=false`}
                    strategy="beforeInteractive"
                />
            </head>
            <Providers>
                <body className={pretendard.className}>
                    <div className="container">
                        <Header />
                        {children}
                        <Footer />
                    </div>
                </body>
            </Providers>
        </html>
    );
}
